WorldEdit transformers for 1.8.8 + give more control to transformers (wrapper)
CloudNetService/CloudNet-v3 pull request #1429
Opened 2024-07-01 16:05 UTC by DasBabyPixel

### Motivation

A few servers running bukkit 1.8.8 still use worldedit. Only since the change to modern java on those old versions, worldedit stopped to work. This PR fixes worldedit and FAWE on 1.8.8.
The necessary class transformers also uncovered a problem in the class transformer api. Converting a `ClassNode` back to a `byte[]` was not possible (in some cases), because of `COMPUTE_FRAMES|COMPUTE_MAXS`.

Some might also want to make use of the wrapper transformer API in wrapper modules, so the custom `byte[]` creation might come in handy.
As an example, I have another project that needs transforming of classes, but uses a `byte[]` instead of asm.
The new API allows something like this:
```
@Override
public byte[] toByteArray(ClassNode classNode) {
    var bytes = Transformer.super.toByteArray(classNode);
    return CustomTransformer.transform(bytes);
}
```

### Modification

Added transformers for WorldEdit / FAWE
Added a custom opt-in serializer option for transformers.
Added better logging for transformer failures.

### Result

FAWE / WorldEdit supported.
Proper handling of transformer errors / soft failure - not doing this causes the JVM to freeze on errors iirc.
Give more control to transformers, without changing their default behaviour.

##### Other context

This is something I concocted some ago and kept in my fork, thought this might be of interest.
I did also test worldedit/fawe on 1.20 to make sure this doesn't cause any problems. Didn't notice anything, but as always with transformers, future changes on worldedit (they'd have to do something odd, but still) could cause the transformer to break worldedit functionality.

If the worldedit transformers aren't merged, I'd still love to see the API to give more control to transformers merged, because I use the API changes privately. WorldEdit transformers could be re-added by a wrapper module, but only with the more powerful api.

2024-07-08 17:54 UTC, 0utplay commented
I like the idea, but this might have to wait until we've replaced the networking and asm

2024-07-14 13:49 UTC, 0utplay commented
If you are still willing to do these changes: You have to use the new classfile api

2024-07-14 15:26 UTC, DasBabyPixel commented
Can I give the ClassTransform class the option (a default method, or sth else) of manually modifying the byte[] of the class after using java's api? I mostly did the whole thing to be able to manually apply papermc transforms to classes contained in a wrapper module.
To do something like this: 
```
@Override
public byte[] toByteArray(ClassNode classNode) {
    var bytes = Transformer.super.toByteArray(classNode);
    return ClassloaderBytecodeModifier.bytecodeModifier().modify(null, bytes);
}
```

2024-07-14 15:28 UTC, DasBabyPixel commented
Maybe I'm also missing a way to do the same thing using java's new api. If so, let me know

2024-07-14 15:47 UTC, 0utplay commented
cc @derklaro

2024-07-14 16:48 UTC, derklaro commented
The wrapper transformer api is build to transform *classes* not to implement custom transformers which, imo, is done with the changes made to the api recently.

If you want to transform the original class bytes of a class, I suggest to either write your own java agent and attach it to register custom transformers, or, another way would be to use a (kinda) hacky approach to get the original class bytes, pass them to your transformer like this:
```java
static class TestClassTransform implements ClassTransform {

  @Override
  public void atStart(ClassBuilder builder) {
    var classModel = builder.original().orElseThrow();
    var classReader = (ClassReader) classModel.constantPool();
    var originalClassBytes = classReader.readBytes(0, classReader.classfileLength());
    // pass to custom transformer, parse the class file & extract the instructions to call from it
  }

  @Override
  public void accept(ClassBuilder builder, ClassElement element) {
    // builder.accept(element); - use this to accept the old class
    // or use the extracted elements above and pass them to the builder
  }
}
```

2024-07-14 16:53 UTC, DasBabyPixel commented
> The wrapper transformer api is build to transform _classes_ not to implement custom transformers which, imo, is done with the changes made to the api recently.
> 
> If you want to transform the original class bytes of a class, I suggest to either write your own java agent and attach it to register custom transformers, or, another way would be to use a (kinda) hacky approach to get the original class bytes, pass them to your transformer like this:
> 
> ```java
> static class TestClassTransform implements ClassTransform {
> 
>   @Override
>   public void atStart(ClassBuilder builder) {
>     var classModel = builder.original().orElseThrow(); // transforming, so this is always present
>     var classReader = (ClassReader) classModel.constantPool();
>     var originalClassBytes = classReader.readBytes(0, classReader.classfileLength());
>     // pass to custom transformer, parse the class file & extract the instructions to call from it
>   }
> 
>   @Override
>   public void accept(ClassBuilder builder, ClassElement element) {
>     // builder.accept(element); - use this to accept the old class
>     // or use the extracted elements above and pass them to the builder
>   }
> }
> ```

Allright, I'm gonna finish the transformers in this PR (they don't need byte[] manipulation). Going to try your suggestion, if an issue arises, I'm gonna open a new issue or PR

2024-07-14 16:55 UTC, derklaro commented
I'm happy to pull in the WorldEdit transformers. If there are issues feel free to contact me on Discord :)

2024-07-14 19:12 UTC, DasBabyPixel commented
Finished the transformers, tested `//pos1 //pos2 //set <block>` on paper 1.8.8, 1.12.2, 1.16.5 and 1.21. 
See commit message for exact versions used

2024-07-15 06:51 UTC, derklaro requested changes
A few minor nits, but generally looking good

2024-07-15 06:51 UTC, derklaro commented on wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/transform/bukkit/FAWEConfigTransformer.java
> +public class FAWEConfigTransformer implements ClassTransformer {
```suggestion
@ApiStatus.Internal
public final class FAWEConfigTransformer implements ClassTransformer {
```
And I would really appreciate if you could add a small javadoc comment to all classes describing what the transformer is doing.

2024-07-15 06:51 UTC, derklaro commented on wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/transform/bukkit/FAWEReflectionUtilsTransformer.java
> +  @Override
`@inheritDoc` is missing on these

2024-07-15 06:51 UTC, derklaro commented on wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/transform/bukkit/FAWEReflectionUtilsTransformer.java
> +      // field.setAccessible(true);
```suggestion
    CodeTransform codeTransform = (builder, _) -> {
      // field.setAccessible(true);
```

2024-07-15 06:51 UTC, derklaro commented on wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/transform/bukkit/FAWEWorldEditDownloadURLTransformer.java
> +    };
we had a recent incident where the constant was loaded using `LDC_W`, i would personally just check if the constant value is a string instead. Also, merging all these ifs should be better:
```suggestion
    CodeTransform codeTransform = (builder, element) -> {
      if (element instanceof ConstantInstruction.LoadConstantInstruction inst
        && inst.constantValue() instanceof String string
        && string.equals(OLD_DOWNLOAD_URL)) {
        builder.ldc(NEW_DOWNLOAD_URL);
        return;
      }
      builder.with(element);
    };
```

2024-07-15 12:09 UTC, DasBabyPixel commented
Done

2024-07-15 13:41 UTC, derklaro approved these changes
didn't test this, but code LGTM

2024-07-15 13:45 UTC, 0utplay commented
I will do some small testing later and merge afterwards. Thank you!

2024-07-15 17:08 UTC, 0utplay commented
So I did face an issue using fawe and the //set Command. 
![image](https://github.com/user-attachments/assets/9dbcb2a6-fec5-42ea-88a3-d22145a03f6b)

But worldedit was working fine and fawe is also working and I think you can argue that people would have to live with that

2024-07-15 17:23 UTC, DasBabyPixel commented
> So I did face an issue using fawe and the //set Command. ![image](https://private-user-images.githubusercontent.com/60936899/348793731-9dbcb2a6-fec5-42ea-88a3-d22145a03f6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjM3MTQsIm5iZiI6MTcyMTA2MzQxNCwicGF0aCI6Ii82MDkzNjg5OS8zNDg3OTM3MzEtOWRiY2IyYTYtZmVjNS00MmVhLTg4YTMtZDIyMTQ1YTAzZjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE3MTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzOGIyYjc4MGU4ZGMxYTk3NWRjYWI2MzA5OTc1YTZiZDQ2MWQzZGI0YTllYTNjMWQ3OTc0Yjc0Y2FkNzhlMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._IbIbfnER7JinNIyPF4H9cfENnOEkx7O1YtXxhGW2aA)
> 
> But worldedit was working fine and fawe is also working and I think you can argue that people would have to live with that

I didn't notice that because I had anti xray turned off. Gonna see if there is an easy fix, otherwise oh well...
I do want to point out that this also happens with java 8 on a pure paper server without anything else

2024-07-15 17:42 UTC, DasBabyPixel commented
After further investigation, this happens because timings are stopped while async (duh). 
FAWE sends chunk updates async and the PacketPlayOutMapChunk hides blocks async, causing this. 
This is not actually an error but rather a warning that also up screws timings a little

![image](https://github.com/user-attachments/assets/172fb006-279b-4be6-9039-56bfd1f61b93)

I see 3 options
Option 1: Disable timings in config
Option 2: Disable anti xray in config
Option 3: Add transformer disabling either

I think it is best to ignore this and tell ppl to change their config to disable timings. We have spark for a reason.

2024-07-15 17:49 UTC, merged