feat: Ability to edit autoDeleteOnStop of a task via commands
CloudNetService/CloudNet-v3 pull request #1453
Opened 2024-07-13 18:35 UTC by RobotHanzo

### Motivation
`tasks task <name> set` was missing the ability to edit `autoDeleteOnStop`

### Modification
Added the command `tasks task <name> set autoDeleteOnStop <enabled>`

### Result
`tasks task <name> set` can now modify `autoDeleteOnStop`, without having to edit the json file by hand

##### Other context
N/A

2024-07-13 19:46 UTC, 0utplay commented
I'm not really sure. When I implemented the commands for v4 I left that one out on purpose because a lot of users do net get what this means and confuse it with `staticServices`. At least until there is no proper documentation I would leave it like it is

2024-07-14 11:23 UTC, RobotHanzo commented
> I'm not really sure. When I implemented the commands for v4 I left that one out on purpose because a lot of users do net get what this means and confuse it with `staticServices`. At least until there is no proper documentation I would leave it like it is

I thought leaving it out from tasks setup would be enough (as this is probably what most starters start with)
Advanced users probably need a convenient method to configure this though (in my opinion)

2024-07-14 11:23 UTC, RobotHanzo commented
> I'm not really sure. When I implemented the commands for v4 I left that one out on purpose because a lot of users do net get what this means and confuse it with `staticServices`. At least until there is no proper documentation I would leave it like it is

I thought leaving it out from tasks setup would be enough (as this is probably what most starters start with)
Advanced users probably need a convenient method to configure this though (in my opinion)

2024-07-15 16:15 UTC, 0utplay requested changes

2024-07-15 16:15 UTC, 0utplay commented on node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
> +      ServiceTask.Builder::maintenance,
I do not think this is right here

2024-07-16 16:40 UTC, RobotHanzo commented on node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
> +      ServiceTask.Builder::maintenance,
> I do not think this is right here

Forgot to change it, fixed

2024-07-16 18:48 UTC, 0utplay approved these changes

2024-07-16 18:52 UTC, merged