feat: minecraft 1.21.4
CloudNetService/CloudNet-v3 pull request #1553
Opened 2024-12-11 08:08 UTC by 0utplay

### Motivation
MC 1.21.4 was released a few days ago. We want to update our platforms to support it properly.

### Modification
Updated downloads, packet events (for npcs) and minestom

### Result
1.21.4 is supported on Fabric, Bukkit, Velocity, Bungee and 1.21.3 on minestom

2024-12-11 10:14 UTC, derklaro requested changes

2024-12-11 10:14 UTC, derklaro commented on modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/minestom/MinestomBridgeManagement.java
> +      _ -> player.getPermissionLevel() > 0);
This should probably use the permission function as well.

2024-12-11 10:14 UTC, derklaro commented on modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/minestom/MinestomBridgeManagement.java
> +    return this.fallback(player.getUuid(), currServer, null, _ -> player.getPermissionLevel() > 0);
This should probably use the permission function as well.

2024-12-11 10:14 UTC, derklaro commented on modules/npcs/build.gradle.kts
> +  }
not needed anymore

2024-12-11 19:27 UTC, derklaro approved these changes

2024-12-11 20:11 UTC, merged

2024-12-14 18:43 UTC, DasBabyPixel commented
Bei MinestomPlayerManagementListener handleLogin ist das PlayerSpawnEvent verwendet. Dadurch wird ein Spieler erst sehr spät im login wegen Wartungsarbeiten gekickt. Wäre AsyncPlayerConfigurationEvent nicht die bessere wahl?