Prevent sync chunk operations in sign system
CloudNetService/CloudNet-v3 pull request #385
Opened 2020-12-13 10:58 UTC by derklaro

This pull request includes:

- [ ] breaking changes
- [X] no breaking changes

### Changes made to the repository:

This pull request prevents the sync load and generate operations to chunks in which cloudsigns are created.

### Documentation of test results:

https://timings.aikar.co/?id=c23f0ed967384c95abc1478986be679d#plugins

### Related issues/discussions:

Closes #381

2020-12-14 15:47 UTC, juliarn requested changes
Looks good, but we should check if these changes can be applied to the NukkitSignManagement too.

2020-12-14 15:47 UTC, juliarn commented on cloudnet-modules/cloudnet-signs/src/main/java/de/dytanic/cloudnet/ext/signs/bukkit/BukkitSignManagement.java
> +        final World world = Bukkit.getWorld(worldPosition.getWorld());
Same as above.

2020-12-14 15:48 UTC, juliarn commented on cloudnet-modules/cloudnet-signs/src/main/java/de/dytanic/cloudnet/ext/signs/bukkit/BukkitSignManagement.java
> +            final Location location = this.toLocation(sign.getWorldPosition());
We don't use final for local variables at any place in this project, so why would we do this here? Imo final on local variables is pretty unnecessary.

2020-12-15 07:02 UTC, derrop approved these changes
Didn't test if it works though

2020-12-15 07:04 UTC, juliarn approved these changes

2020-12-18 14:02 UTC, merged