Moved code for nametags from cloudperms module to simplenametags plugin
CloudNetService/CloudNet-v3 pull request #458
Opened 2021-04-28 08:52 UTC by MCMDEV

This pull request includes:

- [x] breaking changes
- [ ] no breaking changes

### Changes made to the repository:

Moved code for nametag handling from the CloudPerms Module into the SimpleNameTags Plugin.
As a result, the API-accessible updateNameTags methods were moved.
The corresponding example was also updated.

### Documentation of test results:

Changes have been tested on a v3.3.0 Environment, everything works as expected.

### Related issues/discussions:

  
https://github.com/CloudNetService/CloudNet-v3/pull/457 (Original PR, wrong source branch)

2021-05-04 14:00 UTC, derklaro requested changes
Thanks for your pull request! Please note that you are breaking an api by doing this change. Please don't remove the nametags code from the BukkitCloudNetCloudPermissionsPlugin, make the old methods deprecated and scheduled for removal.

2021-05-04 15:08 UTC, Sarsum commented
I think we should also keep in mind that those breaking changes would require everyone to replace their SimpleNameTags Tool in the servers.

2021-06-05 18:01 UTC, derklaro commented
Please rebase to the latest development branch and resolve the merge conflicts, thank you :)

2021-06-06 15:45 UTC, derklaro approved these changes

2021-06-06 15:45 UTC, merged