Added time format into the CloudNet-Report module
CloudNetService/CloudNet-v3 pull request #491
Opened 2021-06-12 20:28 UTC by a6doff

### This pull request includes:

The addition of an option (true by default) to store records into subfolders with the date.

### Changes made to the repository:

Changed only the CloudNet-Report module

### Documentation of test results:

Adds "YYYY-mm-dd" (2021-06-12 for instance) into the records, option can be disabled.
_There definitely is room for optimization especially the call to check if the date has changed every time a server stops._

### Related issues/discussions:

Absolutely none

2021-06-12 20:34 UTC, derklaro requested changes

2021-06-12 20:34 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +    this.getConfig().getString("dateFormat", "YYYY-MM-dd");
I assume this shoul be `yyyy-MM-dd`

2021-06-12 20:34 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +    SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
Can't we create the format once? And why is the config option for the format not used?

2021-06-12 20:34 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +    String getdate = dateFormat.format(new Date());
```suggestion
    String date = dateFormat.format(System.currentTimeMillis());
```

2021-06-12 20:34 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +    SimpleDateFormat dateFormat = new SimpleDateFormat(this.getConfig().getString("dateFormat"));
We should create the format once, not every time

2021-06-12 20:34 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +    if (this.getConfig().getBoolean("addCustomDate") == true) {
```suggestion
    if (this.getConfig().getBoolean("addCustomDate")) {
```

2021-06-12 20:34 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/listener/CloudNetReportListener.java
> +    this.reportModule.initSavingRecordsDirectory();
This should be in the handler of the `CloudServicePreDeleteEvent`

2021-06-13 07:27 UTC, derklaro requested changes

2021-06-13 07:27 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +      String date = dateFormat.format(System.currentTimeMillis());
```suggestion
      String date = this.dateFormat.format(System.currentTimeMillis());
```

2021-06-13 07:27 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +  private SimpleDateFormat dateFormat;
```suggestion
  private DateFormat dateFormat;
```

2021-06-13 07:27 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/listener/CloudNetReportListener.java
> +
```suggestion
```

2021-06-13 07:27 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
>    public void initSavingRecordsDirectory() {
This should no longer be a module task, as we do init the directory inside the `CloudServicePreDeleteEvent`:
```suggestion
  public void initSavingRecordsDirectory() {
```

2021-06-13 07:27 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +    }
```suggestion
    String dateFormat = this.getConfig().getString("dateFormat");
    if (dateFormat != null && this.getConfig().getBoolean("addCustomDate")) {
      this.dateFormat = new SimpleDateFormat(dateFormat);
    }
```

2021-06-13 07:27 UTC, derklaro commented on cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
> +    if (this.getConfig().getBoolean("addCustomDate")) {
```suggestion
    if (this.dateFormat != null && this.getConfig().getBoolean("addCustomDate")) {
```

2021-06-13 15:56 UTC, a6doff commented
@derklaro I merged without thinking that much about it but wouldn't `SimpleDateFormat` be more appropriate?
So people would also be able to add hours and minutes?

2021-06-13 16:14 UTC, derklaro commented
> @derklaro I merged without thinking that much about it but wouldn't `SimpleDateFormat` be more appropriate?
> So people would also be able to add hours and minutes?

That's not how java works. If you create the date format using the `SimpleDateFormat` it will work as expected.

2021-06-13 16:29 UTC, a6doff commented
> > @derklaro I merged without thinking that much about it but wouldn't `SimpleDateFormat` be more appropriate?
> > So people would also be able to add hours and minutes?
> 
> That's not how java works. If you create the date format using the `SimpleDateFormat` it will work as expected.

Yes, it was working as approprite, that's why I'm wondering why you [commited](https://github.com/CloudNetService/CloudNet-v3/pull/491/commits/f0ee1e5d99514e26d1ae086fbe8f21431498713b) to change it to `DateFormat` instead

2021-06-13 16:50 UTC, derklaro commented
> > > @derklaro I merged without thinking that much about it but wouldn't `SimpleDateFormat` be more appropriate?
> > > So people would also be able to add hours and minutes?
> > 
> > That's not how java works. If you create the date format using the `SimpleDateFormat` it will work as expected.
> 
> Yes, it was working as approprite, that's why I'm wondering why you [commited](https://github.com/CloudNetService/CloudNet-v3/pull/491/commits/f0ee1e5d99514e26d1ae086fbe8f21431498713b) to change it to `DateFormat` instead

That's for abstraction reasons.

2021-06-13 18:12 UTC, derklaro approved these changes

2021-06-15 11:18 UTC, a6doff commented
(oops)

2021-06-21 18:38 UTC, a6doff commented
BRO I pushed on the wrong shit

2021-06-25 19:27 UTC, derklaro commented
Thank you!

2021-06-25 19:27 UTC, merged