docs(drive): Document the permission package
CloudNetService/CloudNet-v3 pull request #621
Opened 2022-02-22 18:03 UTC by 0utplay

2022-03-11 07:48 UTC, derklaro requested changes

2022-03-11 07:48 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/DefaultCachedPermissionManagement.java
> +      lockCount.updateAndGet(count -> count > 0 ? count - 1 : 0);
```suggestion
      lockCount.updateAndGet(count -> Math.max(0, count - 1));
```

2022-03-11 07:48 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/DefaultCachedPermissionManagement.java
> +      lockCount.updateAndGet(count -> count > 0 ? count - 1 : 0);
Same thing

2022-03-11 07:48 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/Permissible.java
> + * @see PermissionManagement
```suggestion
```

2022-03-11 07:48 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionCheckResult.java
> + * @see Permissible
```suggestion
```

2022-03-11 07:48 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionManagement.java
> + * @see PermissionGroup
```suggestion
```

2022-03-11 07:48 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionUser.java
> + * @see PermissionManagement
```suggestion
```

2022-03-11 07:48 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionUserGroupInfo.java
>        return this;
```suggestion
      return this.timeOutMillis(System.currentTimeMillis() + unit.toMillis(timeout));
```

2022-03-14 18:25 UTC, robertschuck approved these changes
thanks

2022-03-18 16:26 UTC, derklaro requested changes

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/AbstractPermissible.java
> + * @see PermissionGroup
```suggestion
 * An abstract implementation of a permissble for shared usage.
 *
```

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/AbstractPermissible.java
> +   * Constructs a new abstract permissible which is the underlying base for a permission group or user.
```suggestion
   * Constructs a new abstract permissible instance.
```

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/AbstractPermissible.java
>    public long createdTime() {
Is there any reason to not have the creation time in the Permissble class directly?

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/CachedPermissionManagement.java
> + * permanent caching if desired.
More like: 
```
Represents a permission management instance which maintains a cache for permission users and groups internally to allow faster loading times (for example looking up the user in the cache rather than the database).
```

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/CachedPermissionManagement.java
> +   * is down to 0.
```suggestion
   * Each method call results in incrementing the lock count of the user. It's ensured that the user stays in the cache until the lock count
   * is decreased again and reaches 0. After that event the normal cache invalidation rules of the permission management take effect again.
```

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/CachedPermissionManagement.java
> +   * Each method call results in incrementing the lock count of the group. The group stays in cache until the lock count
Can use the same additional text as above

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/CachedPermissionManagement.java
> +   * remaining locks the user is removed from the cache after a maximum of 5 minutes.
I don't think that we should specifiy the minute count here. I would suggest using the same generified sentence as for the two methods above 🤔

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/CachedPermissionManagement.java
> +   * remaining locks the group is removed from the cache after a maximum of 5 minutes.
Same thing here

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/CachedPermissionManagement.java
> +   * minutes.
and here

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/CachedPermissionManagement.java
> +   * minutes.
you guessed it :)

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/DefaultPermissionManagement.java
> +   * Gets if the permission management can be overwritten. The default implementation of the permission management is
Nit: I think renaming the method (and then the word in the docs) from overwritten to overridden might be better 🤔

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/DefaultPermissionManagement.java
> +   * @return true
I would generify that

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/Permissible.java
> +   * Modifications to this collection are possible, but still require an update using the permission management.
I don't think that advertising the mutability is a good thing 🤔

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/Permissible.java
> +   * Modifications to this map are possible, but still require an update using the permission management.
I don't think that advertising the mutability is a good thing 🤔

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/Permissible.java
> +   * Modifications to this collection are possible, but still require an update using the permission management.
I don't think that advertising the mutability is a good thing 🤔

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/Permissible.java
>        .toList();
Doesn't this fit into one line?

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/Permission.java
> +   * Compares the potency of this permission with the potency of the given permission.
I think we should include a note that this method uses the absolute potency

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/Permission.java
>    public static class Builder {
Missing commment

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/Permission.java
> +     * @return the same instance for chaining.
```suggestion
     * @return the same instance as used to call the method, for chaining.
```
To stay consistent **This applies to all other builder methods as well!**

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionCheckResult.java
> + * <li>{@link #FORBIDDEN} - a negative permission</li>
Indentation + the closing \</li\> can be truncated

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionGroup.java
> +   * Gets whether this group is the default group or not.
Maybe add a note that there might be multiple groups which are marked as default, but always the first group (non-deterministic) gets choosen when the default group is needed

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionGroup.java
> +    /**
Can't comment on the Builder class but the header is missing there

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionGroup.java
> +     * @return the same builder instance for chaining.
```suggestion
     * @return the same instance as used to call the method, for chaining.
```

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionUser.java
>    public @NonNull Collection<String> groupNames() {
Can you recheck if this collection must be modifyable? If not we can use .toList here

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionUser.java
> +    /**
Builder class comment

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionUser.java
> +     * @return the same builder instance for chaining.
```suggestion
     * @return the same instance as used to call the method, for chaining.
```

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionUserGroupInfo.java
> +    /**
Builder class comment

2022-03-18 16:26 UTC, derklaro commented on driver/src/main/java/eu/cloudnetservice/cloudnet/driver/permission/PermissionUserGroupInfo.java
> +     * @return the same instance for chaining.
```suggestion
     * @return the same instance as used to call the method, for chaining.
```

2022-03-18 17:59 UTC, derklaro approved these changes

2022-03-18 18:00 UTC, merged