Add command to manage the docker module config entries
CloudNetService/CloudNet-v3 pull request #653
Opened 2022-04-10 14:15 UTC by derklaro

Adds a command which allows to edit the docker configuration (either the global or task specific one)

2022-04-10 14:34 UTC, 0utplay requested changes

2022-04-10 14:34 UTC, 0utplay commented on modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerCommand.java
> +      new TaskDockerConfig(null, Set.of(), Set.of(), Set.of()));
Cant we use the builder here

2022-04-10 14:34 UTC, 0utplay commented on modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerCommand.java
> +      ($, builder) -> builder.javaImage(new DockerImage(repository, tag, registry, platform)));
Cant we use the docker image builder

2022-04-10 14:34 UTC, 0utplay commented on modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerCommand.java
> +    this.updateDockerConfig(($, builder) -> builder.javaImage(new DockerImage(repository, tag, registry, platform)));
builder here too?

2022-04-10 17:34 UTC, derklaro commented on modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerCommand.java
> +      new TaskDockerConfig(null, Set.of(), Set.of(), Set.of()));
done

2022-04-11 08:05 UTC, 0utplay approved these changes

2022-04-11 08:05 UTC, merged