Feat/minestom support
CloudNetService/CloudNet-v3 pull request #670
Opened 2022-05-29 12:21 UTC by 0utplay

2022-06-14 16:36 UTC, schucko1337 approved these changes
Ok

2022-06-15 07:00 UTC, derklaro requested changes
Small nits

2022-06-15 07:00 UTC, derklaro commented on ext/adventure-helper/src/main/java/eu/cloudnetservice/ext/adventure/AdventureTextFormatLookup.java
> +    FORMATS = List.copyOf(formats.keySet());
We should really re-check if this stays always in order or if we should use something else here

2022-06-15 07:00 UTC, derklaro commented on modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/minestom/MinestomDirectPlayerExecutor.java
> +    this.forEach(player -> player.chat('/' + command));
Can we post this directly to the command manager?

2022-06-15 07:00 UTC, derklaro commented on modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/minestom/MinestomPlayerManagementListener.java
> +    var player = event.getPlayer();
Should move this before the instanceof check

2022-06-15 07:00 UTC, derklaro commented on modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/minestom/listener/MinestomCloudPermissionsPlayerListener.java
> +    var player = event.getPlayer();
Move this before the instanceof check

2022-06-15 07:00 UTC, derklaro commented on modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/PlatformSign.java
> +  private final Function<String, C> lineMapper;
```suggestion
  protected final Function<String, C> lineMapper;
```

2022-06-15 07:00 UTC, derklaro commented on modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomPlatformSign.java
> +    }
Should move this check before the instance retrieve

2022-06-15 07:00 UTC, derklaro commented on modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomPlatformSign.java
> +    var worldPos = this.base.location();
```suggestion

    var worldPos = this.base.location();
```

2022-06-15 07:00 UTC, derklaro commented on modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomSignBlockHandler.java
> +    return NamespaceID.from("minecraft:sign");
Should probably cache this as well instead of re-parsing the string every time

2022-06-15 07:00 UTC, derklaro commented on modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/functionality/SignInteractListener.java
> +
```suggestion
```

2022-06-15 07:00 UTC, derklaro commented on modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/functionality/SignsCommand.java
> +  ) {
```suggestion
  public SignsCommand(@NonNull MinestomSignManagement signManagement) {
```

2022-06-15 07:00 UTC, derklaro commented on plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/MinestomChatExtension.java
> +      throw new UnsupportedOperationException("Unable to read cloudnet-chat format", exception);
```suggestion
      throw new UncheckedIOException("Unable to read cloudnet-chat format", exception);
```

2022-06-15 07:00 UTC, derklaro commented on plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/MinestomChatExtension.java
> +    var node = EventNode.type("cloudnet-chat", EventFilter.PLAYER);
```suggestion

    var node = EventNode.type("cloudnet-chat", EventFilter.PLAYER);
```

2022-06-15 07:00 UTC, derklaro commented on plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/MinestomChatExtension.java
> +    var player = event.getPlayer();
Move this before the instanceof check

2022-06-15 13:43 UTC, derklaro approved these changes

2022-06-15 13:43 UTC, merged