[ci skip] improve report module
CloudNetService/CloudNet-v3 pull request #692
Opened 2022-06-27 14:43 UTC by derklaro

### Motivation
The current report module is a bit messy and doesn't provide *all* the information which might be useful when it comes to support, but stores a lot of data which is in almost all cases not needed at all or doesn't provide any useful data for us to work with.

### Modification
The report module was rewritten with 3 big changes:
 - It now includes all the data which might be useful when it comes to supporting a user
 - It no longer stores the logs and information about services, which is normally not needed and only clutters your hard drive
 - Paste Servers can now be configured much easier, allowing to easily integrate custom paste servers

### Result
The report module is now much better when it comes down to useful support data and does no longer store cluttering data.

2022-06-30 11:13 UTC, 0utplay requested changes

2022-06-30 11:13 UTC, 0utplay commented on modules/report/src/main/java/eu/cloudnetservice/modules/report/command/ReportCommand.java
>        .filter(service -> service.name().equalsIgnoreCase(name))
service -> server

2022-06-30 11:13 UTC, 0utplay commented on modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/SpecificReportDataEmitter.java
> +  public SpecificReportDataEmitter(@NonNull BiConsumer<ReportDataWriter, Collection<T>> sectionTitleDecorator) {
Nullability annotation

2022-06-30 11:13 UTC, 0utplay commented on modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/NodeServerDataEmitter.java
> +        .appendString(value instanceof LocalNodeServer ? " current" : " remote"))
Maybe use local instead of current

2022-07-03 19:38 UTC, robertschuck approved these changes

2022-07-06 07:42 UTC, 0utplay approved these changes

2022-07-06 07:46 UTC, merged