feat: add support for annotated http handlers
CloudNetService/CloudNet-v3 pull request #696
Opened 2022-07-02 08:39 UTC by derklaro

### Motivation
Developing http handlers is currently painful, as handling a http request requires a seperate class per handler or one handler which does a lot of `if`s to check if a specific request path matches a handling path, if the http method matches etc. 

### Modification
Added the possibility to define multiple http handlers in the same class by annotating them and adding some useful functionality to them to make development even easier.

### Result
Develeoping http handlers is now much easiert.

##### Other context
All existing http handlers will be converted in a seperate pull request to not unnecessarily blow up this one.

Example usage of the new system:
```java
    @HttpRequestHandler(paths = "/test/all/{id}", priority = 0)
    public void handleAll(
      // the http call context (this is the only required paramater)
      HttpContext context,
      // this parameter is taken out of the path and required
      @RequestPathParam("id") String id,
      // this parameter is a required header
      @RequestHeader("username") String username,
      // this paramater is an optional header which defaults to null
      @Optional @RequestHeader("pageId") String pageId,
      // this paramater is an optional header, which defaults to "bcc582ed494d4b9386cbb58564651a26" if not given
      @Optional @RequestHeader(value = "uuid", def = "bcc582ed494d4b9386cbb58564651a26") String uuid
    ) {
    }
```

2022-07-02 14:29 UTC, robertschuck approved these changes

2022-07-02 17:09 UTC, 0utplay requested changes
Looks great

2022-07-02 17:09 UTC, 0utplay commented on driver/src/main/java/eu/cloudnetservice/driver/network/http/annotation/parser/HttpAnnotationProcessor.java
> +   * before the actual http handler is called, allowing the parser to modify or event abort the request.
even abort

2022-07-02 17:09 UTC, 0utplay commented on driver/src/main/java/eu/cloudnetservice/driver/network/http/annotation/parser/HttpAnnotationProcessorUtil.java
> +public final class HttpAnnotationProcessorUtil {
No javadoc here?

2022-07-03 11:27 UTC, 0utplay approved these changes

2022-07-03 11:41 UTC, merged