chore: add support for compressed http responses
CloudNetService/CloudNet-v3 pull request #699
Opened 2022-07-02 17:32 UTC by derklaro

### Motivation
Clients can send an `accept-encoding` http header to request a specific encoding of the response, some of them require the server to compress the response (especially useful when trying to f. ex. download files).

### Modification
Add the content compressor handler of netty into the pipeline which automatically compresses the response when requested. (Supported compressions are `gzip`, `deflate`. `zstd` & `br`). 

### Result
We are now compressing http responses when requested.

2022-07-02 17:38 UTC, robertschuck approved these changes

2022-07-03 04:53 UTC, 0utplay requested changes

2022-07-03 04:53 UTC, 0utplay commented on driver/src/test/java/eu/cloudnetservice/driver/network/http/NettyHttpServerTest.java
> +    HttpServer server = new NettyHttpServer();
Use var

2022-07-03 11:27 UTC, 0utplay approved these changes

2022-07-03 11:45 UTC, merged