chore: migrate http handlers to annotation based api
CloudNetService/CloudNet-v3 pull request #710
Opened 2022-07-09 11:51 UTC by derklaro

### Motivation
We recently introduced a new http annotation api and all of our existing handlers should use that api as well as it cleans up a lot of code and is much simpler to understand.

### Modification
 - Migrate all existing http handlers to the annotation based api
 - Fix some request handling inconsistencies
 - Fix wrong `cancelNext` call in all handlers (without a paramater it's a getter not a setter)
 - Remove WebSocket ticket system as it has no benifit
 - Remove file serve http helpers to prevent users from building a file serving server using inbuild api
 - Fix some last issues discovered with the annotation api while migrating

### Result
Much cleaner http handlers and a lot less code overall.

2022-07-09 22:01 UTC, robertschuck approved these changes

2022-07-13 11:08 UTC, 0utplay requested changes

2022-07-13 11:08 UTC, 0utplay commented on modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerCluster.java
> +  @NonNull
Cant we inline the annotation

2022-07-13 11:55 UTC, 0utplay requested changes

2022-07-13 11:55 UTC, 0utplay commented on modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerTemplate.java
> +        this.ok(context).body(this.success().toString()).context().closeAfter(true).cancelNext(true);
Can we reformat this

2022-07-13 12:32 UTC, merged