docs: improve wrapper documentation
CloudNetService/CloudNet-v3 pull request #715
Opened 2022-07-11 13:23 UTC by derklaro

### Motivation
The wrapper documentation is very old and outdated and should be updated.

### Modification
Updated the documentation of the wrapper api and made some very small code changes to enhance the overall api.

### Result
Cleaner & better documented wrapper api.

2022-07-11 18:08 UTC, 0utplay requested changes

2022-07-11 18:08 UTC, 0utplay commented on wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/event/ApplicationPostStartEvent.java
> +   * Get the tread in which the application is running.
thread

2022-07-11 18:10 UTC, derklaro commented on wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/event/ApplicationPostStartEvent.java
> +   * Get the tread in which the application is running.
```suggestion
   * Get the thread in which the application is running.
```

2022-07-15 18:20 UTC, robertschuck approved these changes

2022-07-16 17:07 UTC, 0utplay approved these changes

2022-07-16 17:09 UTC, merged