feat: Allow a host address on a per task basis
CloudNetService/CloudNet-v3 pull request #727
Opened 2022-07-16 08:50 UTC by 0utplay

### Motivation
Currently every service is started on the same host address provided in the node configuration. The problem with this is that there is no way to use different hosts for different tasks like a Proxy and a Lobby.
### Modification
Created a new host address option for tasks which is used to bind the services of the task to. In order to make this feature available in the cluster too (different ips on different host systems), an ip alias system was implemented. The ip aliases are configured on each node and are resolved when starting the service. If somebody wants to use the same ip for each task supplying null as host address will use the fallback host, which is the old approach of using the host address provided by the node.

### Result
All tasks can have different host addresses and bind their services to that host address.

2022-07-16 11:23 UTC, derklaro requested changes
Quick feedback

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/util/NetworkUtil.java
> +    return assignableHostAndPort(hostAndPort);
```suggestion
    // try to parse host and port from the given string
    var hostAndPort = parseHostAndPort(address, withPort);
    return hostAndPort == null ? null : assignableHostAndPort(hostAndPort);
```

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/util/NetworkUtil.java
> +      socket.bind(new InetSocketAddress(hostAndPort.host(), 45555));
```suggestion
      socket.bind(new InetSocketAddress(hostAndPort.host(), 0));
```
Should bind the socket to the next free port

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/util/NetworkUtil.java
> +  public static @Nullable HostAndPort assignableHostAndPort(@NonNull HostAndPort hostAndPort) {
This name seems off - shouldn't it be something like `checkAssignable`?

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/util/NetworkUtil.java
> +  public static @Nullable HostAndPort assignableHostAndPort(@NonNull String address, boolean withPort) {
Same here, the name is off - it should be prefixed with `parse`

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/command/sub/ClusterCommand.java
> +    if (InetAddresses.isInetAddress(address)) {
Hm, maybe we should use our parsing method here as well?

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
> +  public @NonNull String hostAddressParser(@NonNull CommandContext<?> $, @NonNull Queue<String> input) {
A lot of spaces here 😂

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
> +    @NonNull @Argument(value = "hostAddress", parserName = "ipAliasHostAddress") String hostAddress
But with this there is no way to reset the host address? (aside from editing the file)

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/config/JsonConfiguration.java
> +    for (var pair : values) {
Can we move the split directly in the for loop?

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/config/JsonConfiguration.java
> +    return this.ipAliases != null ? this.ipAliases : (this.ipAliases = new HashMap<>());
In theory the ipAliases map should always be present after the call to `load`?

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/setup/SpecificTaskSetup.java
> +            NetworkUtil.availableIPAddresses()
```suggestion
          .possibleResults(() -> NetworkUtil.availableIPAddresses()
```

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/command/sub/ClusterCommand.java
> +    return List.copyOf(NetworkUtil.availableIPAddresses());
(Cannot comment on the method in NetworkUtil so doing it here): Shouldn't we move the `availableIPAddresses` into a static field which gets resolved only once? Especially if we have that many acesses to the list...

2022-07-16 11:23 UTC, derklaro commented on node/src/main/java/eu/cloudnetservice/node/util/NetworkUtil.java
> +  public static @Nullable HostAndPort assignableHostAndPort(@NonNull HostAndPort hostAndPort) {
Any maybe return a boolean 🤔

2022-07-17 09:21 UTC, derklaro approved these changes

2022-07-17 12:24 UTC, robertschuck approved these changes

2022-07-17 12:39 UTC, merged