Fixed server kick
CloudNetService/CloudNet-v3 pull request #853
Opened 2022-09-14 18:15 UTC by MenschenToaster

### Motivation
When a server kicks a player while logging in and the player wants to join again the player will get kicked from the network stating that no lobby server could be found.

### Modification

In Velocity I moved the notify result code so it runs before fallbacks are getting queried. In Bungeecord I tried to implement the same functionallity altough I haven't tested that yet and don't have much experience with the Bungeecord-API. 

### Result

This PR stops the player from getting kicked from the entire network as long as the player has an active connection to a server.

##### Other context

2022-09-15 05:26 UTC, derklaro requested changes

2022-09-15 05:26 UTC, derklaro commented on modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordPlayerManagementListener.java
> +      if (event.getState() == ServerKickEvent.State.CONNECTING && event.getPlayer().getServer() != null) {
Please keep the code consistent with the velocity one:
 * Extract the current server into a variable
 * Please add a comment why we're doing this
 * Please add a blank line after the if block

2022-09-15 05:26 UTC, derklaro commented on modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordPlayerManagementListener.java
> +    Locale playerLocale = event.getPlayer().getLocale();
```suggestion
    var playerLocale = event.getPlayer().getLocale();
```

2022-09-15 05:26 UTC, derklaro commented on modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/velocity/VelocityPlayerManagementListener.java
> +      // only notify the player if the player was kicked on login and is already connected to a server
```suggestion
      // only notify the player if the player was kicked on login and is already connected to a server
      var curServer = event.getPlayer().getCurrentServer().orElse(null);
```

2022-09-15 05:50 UTC, derklaro commented
Although this introduces another issue as well. If you're getting kicked during the connect to a fallback server, there are no further attempts to connect you to any other fallback service. The current code only sends the message if you're already connected to a fallback service. So I would prefer clearing the fallback profile of the player before the notify rather than changing the code in this way.

2022-09-15 06:12 UTC, MenschenToaster commented
> Although this introduces another issue as well. If you're getting kicked during the connect to a fallback server, there are no further attempts to connect you to any other fallback service. The current code only sends the message if you're already connected to a fallback service. So I would prefer clearing the fallback profile of the player before the notify rather than changing the code in this way.

Well I think it depends. When you are doing /hub and maybe have an issue connecting I see why this is an issue. But is it really a good idea sending the player to a fallback when any login connection error occurs? I don't think the proxies do that by default and I see no reason it should behave that way(well except in the /hub case)

2022-09-15 08:00 UTC, derklaro commented
I'm always pro improving stuff, but this seems to (at the current point) introduce even more issues 🤔

2022-09-15 13:46 UTC, MenschenToaster commented
> I'm always pro improving stuff, but this seems to (at the current point) introduce even more issues 🤔

Is there any other issue then the /hub command only connecting to one server? Because if thats the only issue this stuff could be implemented in the hub command directly

2022-09-15 19:41 UTC, 0utplay commented
Could you try using the change @derklaro made?

`fix-invalid-fallback-profile-entries` is the branch that contains the change.

2022-09-16 12:26 UTC, MenschenToaster commented
> Could you try using the change @derklaro made?
> 
> `fix-invalid-fallback-profile-entries` is the branch that contains the change.

It does work, but with more than one fallback running, you get thrown around from one fallback to another. On my branch you would remain on the same one, which is better to look at and saves some performance because the login process is pretty demanding

2022-09-16 12:58 UTC, derklaro commented
I don't get what you're testing, but based on my fix I don't understand how you would get thrown around...

2022-09-16 14:29 UTC, MenschenToaster commented
> I don't get what you're testing, but based on my fix I don't understand how you would get thrown around...

With one Lobby/fallback server there, your fix behaves exactly like mine. 
And the original issue is fixed on your branch too, but the behavior still annoys me a bit.

When there are two fallback servers e.g. Lobby-1 and Lobby-2 and you want to connect to a game server, but the game server doesn't let you in for whatever reason.(e.g. it's full) If you are on Lobby-1 you will get sent to Lobby-2 after the connection error occurred. If you are on Lobby-2 you will be sent to Lobby-1. In my opinion, these are just unnecessary connections that are happening since you are already connected to a fallback. 

Or let's say you are on a Hypixel Skyblock like Server and want to connect to your Island (which is on a different sub-server) and a connection error occurs. Instead of remaining in the skyblock hub and receiving an error, you will end up in the main hub. I just don't like that behavior.

2022-09-18 13:03 UTC, derklaro commented
> If you are on Lobby-2 you will be sent to Lobby-1. In my opinion, these are just unnecessary connections that are happening since you are already connected to a fallback.

Correct, but it still seems to me that your fix is adding an unexpected behaviour if a fallback service is rejecting a player connection. Consider the following: A BedWars game ended, the server is kicking all the players, the lobby server is rejecting the connection (for example because it's full) & the players stays on the BedWars service. The connection to the server times out but there are no attemps made to connect the player to a different fallback.

> Or let's say you are on a Hypixel Skyblock like Server and want to connect to your Island (which is on a different sub-server) and a connection error occurs. Instead of remaining in the skyblock hub and receiving an error, you will end up in the main hub. I just don't like that behavior.

That is wrong & fixed with my proposed fix.

2022-09-18 17:06 UTC, MenschenToaster commented
> A BedWars game ended, the server is kicking all the players, the lobby server is rejecting the connection (for example because it's full) & the players stays on the BedWars service

But wouldn't the connection be closed, and the kick event code is forced to search for a new one? Because my changes would only apply if the player has an active connection. 


> That is wrong & fixed with my proposed fix.

It isn't. If you are on SubServer-1 and want to connect to SubServer-2, but an error occurs, you will be connected to a fallback Lobby. And in my SkyBlock example, this would be the same scenario.

2022-09-19 14:14 UTC, 0utplay commented
I just tested this and there is now way to leave a service using /hub if the first fallback does not accept the request. You are basically stuck on the service.

2022-09-19 15:45 UTC, davidmayr commented
> I just tested this and there is now way to leave a service using /hub if the first fallback does not accept the request (but there is another that could accept it). You are basically stuck on the service.

That is solvable, though, by implementing/modifying the callback in the hub command and making it search for more servers.

2022-09-19 18:32 UTC, derklaro commented
But this would require every plugin to adopt to your change, and every plugin to manually maintain the tried fallbacks of the player which can be a pitfall if you're not doing that carefully. I don't think that in the current state we can/should accept this pull request.

2022-09-19 18:32 UTC, closed without merging